import { z } from 'zod';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import { database, getRecord, readDesk, saveRecord } from '@/lib/store';
import { canonical, hash, intake } from '@/lib/intake';
const text=z.string().max(12000);const short=z.string().max(500);const url=z.string().max(2500).refine(s=>!s||(()=>{try{canonical(s);return true}catch{return false}})(),'Use a valid public HTTPS URL');const date=z.string().refine(s=>!s||/^\d{4}-\d{2}-\d{2}$/.test(s),'Use YYYY-MM-DD');
const opening=z.object({id:short.optional(),schoolId:short,department:short,title:short.min(1),sourceUrl:url.refine(Boolean),applicationUrl:url.default(''),deadline:date.default(''),deadlineType:short.default('Unknown'),deadlineText:text.default(''),hardDeadline:date.default(''),rank:short.default('Unknown'),areas:text.default(''),materials:text.default(''),letters:short.default(''),summary:text.default(''),checkedAt:date.default(''),verification:short.default('Unverified'),hiringStatus:z.enum(['Open','Closed','Unverified']).default('Unverified'),workflow:z.enum(['Inbox','Considering','Preparing','Applied','Interviewing','Offer','Archived']).default('Inbox'),notes:text.default(''),sourceKind:short.default('Research')});
const school=z.object({id:short.min(1),name:short.min(1),shortName:short.min(1),country:short.default('US'),location:short.default(''),domain:short.default(''),considering:z.boolean().default(false),departments:z.array(short).max(15),sources:z.array(z.object({department:short,url:url.refine(Boolean),note:text.optional(),checkedAt:date.optional()})).max(30).default([]),notes:text.default(''),rankingNote:text.default('Membership not verified'),rankingSources:z.array(z.object({name:short,url,rank:z.number().optional(),year:short.optional()})).optional(),origin:short.default('Research')});
async function authorized(request:Request,write=false){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in to access your private search desk.'},{status:401});try{await database().prepare('INSERT OR IGNORE INTO records(id,kind,data,revision,updated_at) VALUES(?,?,?,1,?)').bind('meta:owner','meta',JSON.stringify({userId:user.userId}),new Date().toISOString()).run();const owner=await getRecord('meta','owner');if(owner?.userId!==user.userId)return Response.json({error:'This private desk belongs to a different account.'},{status:403});}catch{return Response.json({error:'Saved data is temporarily unavailable. Please retry.'},{status:503});}if(write){const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return Response.json({error:'Invalid request origin'},{status:403});}return null;}
export async function GET(request:Request){const denied=await authorized(request);if(denied)return denied;try{return Response.json(await readDesk(),{headers:{'Cache-Control':'no-store'}})}catch(e){console.error(e);return Response.json({error:'Your saved data is temporarily unavailable. Please retry.'},{status:503});}}
export async function POST(request:Request){const denied=await authorized(request,true);if(denied)return denied;try{if(Number(request.headers.get('content-length')||0)>250000)return Response.json({error:'Request too large'},{status:413});const payload=await request.text();if(payload.length>250000)throw new Error('Request too large');const p=JSON.parse(payload);const desk=await readDesk();let result:any;
switch(p.action){
 case 'intake':{const r=await intake(url.parse(p.url),desk);if(!r.existing){await saveRecord('request',r.request!.id,r.request);await saveRecord('opening',r.opening!.id,r.opening);}result=r;break;}
 case 'save_opening':{const d=opening.parse(p.data);if(!d.id)throw new Error('Select an opening');if(!desk.schools.some(s=>s.id===d.schoolId)&&d.schoolId!=='unassigned')throw new Error('Choose an existing school');result=await saveRecord('opening',d.id,d,z.number().parse(p.revision));break;}
 case 'save_school':{const d=school.parse(p.data);result=await saveRecord('school',d.id,d,z.number().parse(p.revision));break;}
 case 'research_schools':{const items=z.array(school).max(100).parse(p.schools);for(const d of items){const old=await getRecord('school',d.id);await saveRecord('school',d.id,{...d,...(old?{considering:old.considering,notes:old.notes,origin:old.origin}: {})},old?.revision);}result={updated:items.length};break;}
 case 'stage_openings':{const rawItems=z.array(z.record(z.unknown())).max(60).parse(p.openings);let added=0,updated=0;for(const raw of rawItems){const d=opening.parse(raw);if(!desk.schools.some(s=>s.id===d.schoolId))throw new Error('Add the school before staging its openings');const normalized=canonical(d.applicationUrl||d.sourceUrl);const current=desk.openings.find(o=>o.schoolId===d.schoolId&&o.department.toLowerCase()===d.department.toLowerCase()&&(o.id===d.id||(d.applicationUrl?canonical(o.applicationUrl||o.sourceUrl)===normalized:canonical(o.sourceUrl)===normalized&&o.title.trim().toLowerCase()===d.title.trim().toLowerCase())));const id=current?.id||await hash(d.schoolId+'|'+d.department.toLowerCase()+'|'+normalized+(d.applicationUrl?'':'|'+d.title.trim().toLowerCase()));const old=await getRecord('opening',id);const supplied=Object.fromEntries(Object.keys(raw).filter(k=>k in d).map(k=>[k,(d as any)[k]]));const merged=opening.parse(old?{...old,...supplied}:d);const saved=await saveRecord('opening',id,{...merged,id,workflow:old?.workflow||'Inbox',notes:old?.notes||''},old?.revision);if(old)updated++;else added++;const i=desk.openings.findIndex(o=>o.id===id);if(i>=0)desk.openings[i]=saved;else desk.openings.push(saved);}result={added,updated};break;}
 case 'complete_requests':{const ids=z.array(short).max(100).parse(p.ids);for(const id of ids){const r=await getRecord('request',id);if(!r)continue;await saveRecord('request',id,{...r,status:'Researched'},r.revision);const draft=await getRecord('opening','intake-'+id);if(draft?.verification.startsWith('Draft')&&draft.workflow==='Inbox')await saveRecord('opening',draft.id,{...draft,workflow:'Archived',summary:'Research completed. See the verified opening records or research log for the result.'},draft.revision);}result={completed:ids.length};break;}
 case 'record_run':{const data=z.object({id:short,date:short,summary:text,checked:z.number().int().nonnegative(),newOpenings:z.number().int().nonnegative(),failures:z.array(text).max(150),sources:z.array(url).max(300).optional()}).parse(p.data);result=await saveRecord('run',data.id,data);break;}
 case 'settings':{const settings=z.object({scope:text,rankingRule:text,schedule:text}).parse(p.data);result=await saveRecord('settings','main',settings);break;}
 default:throw new Error('Unknown action');}
return Response.json({result});}catch(e){console.error(e);return Response.json({error:e instanceof z.ZodError?e.issues.map(i=>i.path.join('.')+': '+i.message).join('; '):(e as Error).message||'Unable to save. Your input has been preserved.'},{status:400});}}
